### ISSUE TITLE
Server error 500

### ISSUE THREAD

**Issue by xusmcxjasonx** [FatihKoz/DisposableBasic#1]
Currently just installed 3.0.3 but when it goes to run phpvms updater it just server 500's
Running latest dev build of phpvms.

**Comment by FatihKoz** [comment]
Latest release is 3.0.3

You need to provide more details than just "server 500".

And there is note about a known phpvms v7 core bug in the readme https://github.com/FatihKoz/DisposableBasic#installation-and-updates

Either way, provide debug details or laravel log containing the error itself.

**Comment by xusmcxjasonx** [comment]
SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP INDEX `disposable_randomflight_id_index`; check that it exists (SQL: alter table `phpvms_disposable_randomflight` drop index `disposable_randomflight_id_index`)

**Comment by xusmcxjasonx** [comment]
I almost wonder if the phpvms_ prefix is causing the issue.

**Comment by FatihKoz** [comment]
What is your database engine and version of it ?

Probably, but it should be handled by laravel itself (with the database connection code used by all other parts)

**Comment by xusmcxjasonx** [comment]
10.3.31-MariaDB-log-cll-lve - MariaDB Server

**Comment by xusmcxjasonx** [comment]
if it helps at all

![Screenshot_1](https://user-images.githubusercontent.com/76757225/144688316-7bac655c-c211-4cc9-a8d3-98a1e48d3c0c.png)

**Comment by FatihKoz** [comment]
I know the file, just trying to find why it fails when a prefix is used.

Until I figure it out, you can ;

* Edit all migration files and change ONLY `dropIndex` and `dropUnique` commands to reflect your prefix. There should be 4 files using those commands.

or

* Remove the prefix completely (if this is a new/fresh install and when you have nothing to loose in the database)

**Comment by xusmcxjasonx** [comment]
Okay, i just set it up so no loss there, will try again in a minute

**Comment by FatihKoz** [comment]
Yeah it will be great 'cause if the prefix is causing issues here, it will cause some other problems later on too.

**Comment by FatihKoz** [comment]
If you need to use prefix for the tables, just let me know so I can send the files to you directly. I have the fix for it, now migrations work with or without prefixes...

If not just use the no prefix setup, so I can it further on to see if it causes any more troubles.

**Comment by FatihKoz** [comment]
Closed with commit https://github.com/FatihKoz/DisposableBasic/commit/cf2d9e24b7845a9a56080aa5d6b0574b0a21819f and release [v3.0.4](https://github.com/FatihKoz/DisposableBasic/releases/tag/v3.0.4)
