### ISSUE TITLE
Updates to LYBE airport runways

### ISSUE THREAD

**Issue by abuelo007X** [FatihKoz/DisposableBasic#15]
I wasn't sure how to share this, so just created an Issues as the file in the repository is a zip file.

Renaming two and adding the new ones

INSERT INTO `disposable_runways` (`id`, `airport_id`, `runway_ident`, `lat`, `lon`, `heading`, `lenght`, `ils_freq`, `loc_course`, `airac`, `created_at`, `updated_at`) VALUES
(24828, 'LYBE', '12L', '44.826519', '20.290969', '117', '3400', '110.30', '117', '2014', NULL, '2023-12-02 00:45:39'),
(24829, 'LYBE', '30R', '44.812239', '20.323167', '297', '3400', '109.90', '297', '2014', NULL, '2023-12-02 00:41:51'),
(35132, 'LYBE', '30L', '44.810777', '20.321972', '297', '3500', NULL, NULL, '2312', '2023-12-02 00:38:02', '2023-12-02 00:43:58'),
(35133, 'LYBE', '12R', '44.821611', '20.297416', '117', '3500', '109.50', '117', '2312', '2023-12-02 00:45:31', '2023-12-02 00:46:39');

**Comment by FatihKoz** [comment]
This is what module provides as additional data with `Airac 2311`.

```
(26849, 'LYBE', '12L', '44.826519', '20.290969', '122', '03400', '110.30', '117', '2311', NULL, NULL),
(26850, 'LYBE', '12R', '44.821711', '20.297275', '122', '03500', '109.50', '117', '2311', NULL, NULL),
(26851, 'LYBE', '30L', '44.810778', '20.321919', '302', '03500', NULL, NULL, '2311', NULL, NULL),
(26852, 'LYBE', '30R', '44.812239', '20.323167', '302', '03400', '109.90', '297', '2311', NULL, NULL),
```

I would suggest you to check the latest file.

Closing the issue as this (provided data) is something optional :)
