### ISSUE TITLE
*Feature* - Show HUBs filtering by Airline

### ISSUE THREAD

**Issue by sarcas31** [FatihKoz/DisposableBasic#23]
If possible, have the option to mark the hubs individually for each airline. In the frontend, it should be possible to view the hubs of each airline separately, even if some hubs are shared between multiple airlines.

**Comment by FatihKoz** [comment]
Hi, unfortunately this is not possible with current structure of phpvms v7,
additional fields and relationships are necessary (some should be done at
phpvms v7 itself).

Basically this can be possible but not something on module level at the
moment.
Sent from mobile device / Mobil cihaz ile gönderildi

22 Ağu 2024 Per 11:28 tarihinde sarcas31 ***@***.***> şunu
yazdı:

**Comment by sarcas31** [comment]
Ok, thank you for your answer. Good look!

**Comment by FatihKoz** [comment]
Just for your info, a similar, almost same idea is also present in phpvms v7 main repository.

https://github.com/nabeelio/phpvms/issues/1505
