### ISSUE TITLE
Taxi-in Gates API

### ISSUE THREAD

**Issue by setri100** [FatihKoz/DisposableBasic#24]
Hey Fatih,
I can access my VA‘s latest PIREPS using the API endpoints with a service key (I‘m not admin, just developing a tool for the VA). I‘d like to see the taxi-in gate at the destination as displayed on my VA‘s website also in the PIREP. The information must be stored somewhere since I see it on the website but I do not see it in the PIREP via the API. Any chance to get the information? 

Best wishes!
Seb

**Comment by FatihKoz** [comment]
Hi Sebastian,

Yes it is stored in pirep field values, it depends on the pilot's sceneries and scan (for vmsAcars) but it is not being carried over to the next pirep or aircraft tables.

Something like below will give you both departure and arrival gates/runways;

```php
[
  'dep_position' => optional($pirep->field_values->firstWhere('slug', 'departure-gate'))->value,
  'arr_position' => optional($pirep->field_values->firstWhere('slug', 'arrival-gate'))->value,
  'dep_runway' => optional($pirep->field_values->firstWhere('slug', 'departure-runway'))->value,
  'arr_runway' => optional($pirep->field_values->firstWhere('slug', 'arrival-runway'))->value,
]
```

As you can see from below output, parking stands can be null (not scanned properly, scenery changed, scenery not compatible, pilot parked outside of the stand range etc.) And the text comes directly from the sim/scenery.

![image](https://github.com/user-attachments/assets/8646eb0a-ebf0-41be-b574-e0cf356e2570)

I added them to the controller, you can check and replicate on your end too.

https://github.com/FatihKoz/DisposableBasic/blob/0fdb6f786cd213a519611e0326618d404533c10d/Http/Controllers/DB_ApiController.php#L150-L151

https://github.com/FatihKoz/DisposableBasic/blob/0fdb6f786cd213a519611e0326618d404533c10d/Http/Controllers/DB_ApiController.php#L157-L158

Hope this help.

**Comment by setri100** [comment]
Hey Fatih, that was super fast and indeed helped a lot, I was able to continue with my project thanks to your update! Thanks! In the briefing page for my VA, the briefing distinguishes between a "flight number" and an "ATC callsign". It's identical for 99% of the flights, but there're exceptions. Can the "ATC callsign" also be fetched from the (live) PIREP via API?

**Comment by FatihKoz** [comment]
Hi Sebastian,

Unfortunately, pirep model does not have the callsign and it is not stored. Callsign is only provided with the flight model (as an additional info to pilots for flight planning) and can be changed during online sessions (IVAO/VATSIM etc.).

It is still possible to get the callsign provided for that flight via relationships but there is a chance that it will not be used by the pilot or something else being used if this is an online flight.

Something like below in the controller can give you the callsign of the flight in theory;

```php
'flight_csign' => optional($pirep->airline)->icao . optional($pirep->flight)->callsign,
```

If the callsign is not defined in flight model, you will have only the airline icao code like `DLH` or `STW` only, so be careful :) 

If you want to have something more realistic for your live flights, I would suggest using the network feed (provided by the network or by my WhazzUp widget) in a way fulfilling your needs.

Hope this helps
