### ISSUE TITLE
Fuel Calculator Syntax Error + Reference Error

### ISSUE THREAD

**Issue by arv187** [FatihKoz/DisposableBasic#8]
`\phpvms\modules\DisposableBasic\Resources\views\widgets\fuel_calculator.blade.php`
When Calculate button is clicked, nothing happens and two errors are showed in console browser:

`Uncaught SyntaxError: Unexpected token ';' (EC-ZAB:372)`
`Uncaught ReferenceError: FuelCalculator is not defined
    at HTMLButtonElement.onclick (EC-ZAB:358:137)`

I tried with different navigators, firefox default and edge. W10. With laravel config in locale es and en.
Too with Linux OS in virtual machine with Tor Browser conection = Canada, env.php locale=en
And with Zorin OS other Linux OS distro in my laptop with firefox, LibreWolf and Chromium.
In all cases, same issue.

![SyntaxError](https://user-images.githubusercontent.com/16170732/185845333-73c17e1a-762e-4278-98a2-9c2978d4cec2.PNG)

Edge Explorer Debug Console
====================================
`get value: ƒ value()
length: 0
name: "get value"
arguments: [Excepción: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.invokeGetter (<anonymous>:3:28) at HTMLButtonElement.onclick (https://argavirtual.com/daircraft/EC-ZAB:358:137)]
caller: [Excepción: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.invokeGetter (<anonymous>:3:28) at HTMLButtonElement.onclick (https://argavirtual.com/daircraft/EC-ZAB:358:137)]
[[Prototype]]: ƒ ()
[[Scopes]]: Scopes[0]
set value: ƒ value()
[[Prototype]]: Node`

I don't know how to fix the error, but I identify the origin and apply a shortcut setting the value to false:

![Fixed](https://user-images.githubusercontent.com/16170732/185845447-7bf12992-ff39-4665-838d-e1c9875b01d3.PNG)
![Fixed2](https://user-images.githubusercontent.com/16170732/185845464-37987cda-296d-4d95-9589-63cafd35f546.PNG)

**Comment by FatihKoz** [comment]
So finally the problem is more clear, it was the metric boolean causing all this.

I think we can make it more clear instead of 0 / 1.

Will look into it, thanks for the feedback @arv187

**Comment by FatihKoz** [comment]
I think below change will fix it 

https://github.com/FatihKoz/DisposableBasic/blob/ffd7d74e633d834f7f15d2a169a73c6b1ab6d4be/Resources/views/widgets/fuel_calculator.blade.php#L86

If possible please try to change your copy according to above.

**Comment by arv187** [comment]
Working Great now!! Thanks for fix.

**Comment by FatihKoz** [comment]
Fixed the JS issue with v3.1.7
